export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_START = "FETCH_PRODUCTS_START";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAIL = "FETCH_PRODUCTS_FAIL";

export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCT_START = "FETCH_PRODUCT_START";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL";

export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const RESET_PRODUCT = "RESET_PRODUCT";

export const SAVE_PRODUCT = "SAVE_PRODUCT";
export const SAVE_PRODUCT_START = "SAVE_PRODUCT_START";
export const SAVE_PRODUCT_SUCCESS = "SAVE_PRODUCT_SUCCESS";
export const SAVE_PRODUCT_FAIL = "SAVE_PRODUCT_FAIL";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_START = "DELETE_PRODUCT_START";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const FETCH_PRODUCT_AUDIT_LOGS = "FETCH_PRODUCT_AUDIT_LOGS";
export const FETCH_PRODUCT_AUDIT_LOGS_START = "FETCH_PRODUCT_AUDIT_LOGS_START";
export const FETCH_PRODUCT_AUDIT_LOGS_SUCCESS =
  "FETCH_PRODUCT_AUDIT_LOGS_SUCCESS";
export const FETCH_PRODUCT_AUDIT_LOGS_FAIL = "FETCH_PRODUCT_AUDIT_LOGS_FAIL";
