
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - src/UIs/vuejs

resources:
- repo: self

variables:
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    displayName: Build VueJs
    pool:
      vmImage: ubuntu-latest
    steps:
    - checkout: self
    - task: NodeTool@0
      displayName: Use Node 12.x
      inputs:
        versionSpec: 12.x
        checkLatest: true
    - task: Npm@1
      displayName: npm install
      inputs:
        workingDir: src/UIs/vuejs
    - task: Npm@1
      displayName: npm audit --audit-level=high
      inputs:
        command: 'custom'
        workingDir: 'src/UIs/reactjs'
        customCommand: 'audit --audit-level=critical'
    - task: Npm@1
      displayName: run build
      inputs:
        command: custom
        workingDir: src/UIs/vuejs
        customCommand: run build
    - task: ArchiveFiles@2
      displayName: Archive
      inputs:
        rootFolderOrFile: 'src/UIs/vuejs/dist'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/vuejs.$(Build.BuildId).zip'
        replaceExistingArchive: true
    - task: PublishPipelineArtifact@1
      displayName: Publish Pipeline Artifact
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)'
        artifact: 'VueJs'
        publishLocation: 'pipeline'