/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    CopyToClipboard: typeof import('./src/components/CopyToClipboard.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Star: typeof import('./src/components/Star.vue')['default']
    Timer: typeof import('./src/components/Timer.vue')['default']
  }
}
