export const UPDATE_FILE = "UPDATE_FILE";
export const RESET_FILE = "RESET_FILE";

export const FETCH_FILES = "FETCH_FILES";
export const FETCH_FILES_START = "FETCH_FILES_START";
export const FETCH_FILES_SUCCESS = "FETCH_FILES_SUCCESS";
export const FETCH_FILES_FAIL = "FETCH_FILES_FAIL";

export const FETCH_FILE = "FETCH_FILE";
export const FETCH_FILE_START = "FETCH_FILE_START";
export const FETCH_FILE_SUCCESS = "FETCH_FILE_SUCCESS";
export const FETCH_FILE_FAIL = "FETCH_FILE_FAIL";

export const SAVE_FILE = "SAVE_FILE";
export const SAVE_FILE_START = "SAVE_FILE_START";
export const SAVE_FILE_SUCCESS = "SAVE_FILE_SUCCESS";
export const SAVE_FILE_FAIL = "SAVE_FILE_FAIL";

export const DELETE_FILE = "DELETE_FILE";
export const DELETE_FILE_START = "DELETE_FILE_START";
export const DELETE_FILE_SUCCESS = "DELETE_FILE_SUCCESS";
export const DELETE_FILE_FAIL = "DELETE_FILE_FAIL";

export const DOWNLOAD_FILE = "DOWNLOAD_FILE";
export const DOWNLOAD_FILE_START = "DOWNLOAD_FILE_START";
export const DOWNLOAD_FILE_SUCCESS = "DOWNLOAD_FILE_SUCCESS";
export const DOWNLOAD_FILE_FAIL = "DOWNLOAD_FILE_FAIL";

export const FETCH_FILE_AUDIT_LOGS = "FETCH_FILE_AUDIT_LOGS";
export const FETCH_FILE_AUDIT_LOGS_START = "FETCH_FILE_AUDIT_LOGS_START";
export const FETCH_FILE_AUDIT_LOGS_SUCCESS = "FETCH_FILE_AUDIT_LOGS_SUCCESS";
export const FETCH_FILE_AUDIT_LOGS_FAIL = "FETCH_FILE_AUDIT_LOGS_FAIL";
