export const FETCH_USERS = "FETCH_USERS";
export const FETCH_USERS_START = "FETCH_USERS_START";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";

export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_START = "FETCH_USER_START";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL = "FETCH_USER_FAIL";

export const UPDATE_USER = "UPDATE_USER";
export const RESET_USER = "RESET_USER";

export const SAVE_USER = "SAVE_USER";
export const SAVE_USER_START = "SAVE_USER_START";
export const SAVE_USER_SUCCESS = "SAVE_USER_SUCCESS";
export const SAVE_USER_FAIL = "SAVE_USER_FAIL";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_START = "DELETE_USER_START";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";

export const FETCH_USER_AUDIT_LOGS = "FETCH_USER_AUDIT_LOGS";
export const FETCH_USER_AUDIT_LOGS_START = "FETCH_USER_AUDIT_LOGS_START";
export const FETCH_USER_AUDIT_LOGS_SUCCESS = "FETCH_USER_AUDIT_LOGS_SUCCESS";
export const FETCH_USER_AUDIT_LOGS_FAIL = "FETCH_USER_AUDIT_LOGS_FAIL";

export const SET_PASSWORD = "SET_PASSWORD";
export const SET_PASSWORD_INIT = "SET_PASSWORD_INIT";
export const SET_PASSWORD_START = "SET_PASSWORD_START";
export const SET_PASSWORD_SUCCESS = "SET_PASSWORD_SUCCESS";
export const SET_PASSWORD_FAIL = "SET_PASSWORD_FAIL";

export const SEND_PASSWORD_RESET_EMAIL = "SEND_PASSWORD_RESET_EMAIL";
export const SEND_PASSWORD_RESET_EMAIL_INIT = "SEND_PASSWORD_RESET_EMAIL_INIT";
export const SEND_PASSWORD_RESET_EMAIL_START =
  "SEND_PASSWORD_RESET_EMAIL_START";
export const SEND_PASSWORD_RESET_EMAIL_SUCCESS =
  "SEND_PASSWORD_RESET_EMAIL_SUCCESS";
export const SEND_PASSWORD_RESET_EMAIL_FAIL = "SEND_PASSWORD_RESET_EMAIL_FAIL";

export const SEND_EMAIL_ADDRESS_CONFIRMATION_EMAIL =
  "SEND_EMAIL_ADDRESS_CONFIRMATION_EMAIL";
export const SEND_EMAIL_ADDRESS_CONFIRMATION_EMAIL_INIT =
  "SEND_EMAIL_ADDRESS_CONFIRMATION_EMAIL_INIT";
export const SEND_EMAIL_ADDRESS_CONFIRMATION_EMAIL_START =
  "SEND_EMAIL_ADDRESS_CONFIRMATION_EMAIL_START";
export const SEND_EMAIL_ADDRESS_CONFIRMATION_EMAIL_SUCCESS =
  "SEND_EMAIL_ADDRESS_CONFIRMATION_EMAIL_SUCCESS";
export const SEND_EMAIL_ADDRESS_CONFIRMATION_EMAIL_FAIL =
  "SEND_EMAIL_ADDRESS_CONFIRMATION_EMAIL_FAIL";
