pipeline {
  agent any
  environment {
    VERSION = "1.0.0.${BUILD_NUMBER}"
  }
  stages {
    stage('Git Checkout') {
      steps {
        git branch: 'master', url: 'https://github.com/phongnguyend/Practical.CleanArchitecture'
      }
    }
    stage('Build') {
      steps {
        sh 'dotnet --info'
		echo "BUILD_NUMBER: ${BUILD_NUMBER}"
		echo "VERSION: ${VERSION}"
        dir('src/Monolith') {
          sh 'dotnet clean'
          sh "dotnet build -p:Version=${VERSION} --configuration Release"
        }
      }
    }
    stage('Publish') {
      steps {
        dir('src/Monolith') {
          sh "dotnet publish -p:Version=${VERSION} ClassifiedAds.Background/*.csproj --configuration Release"
          sh "dotnet publish -p:Version=${VERSION} ClassifiedAds.Migrator/*.csproj --configuration Release"
          sh "dotnet publish -p:Version=${VERSION} ClassifiedAds.WebAPI/*.csproj --configuration Release"
          sh "dotnet publish -p:Version=${VERSION} ClassifiedAds.WebMVC/*.csproj --configuration Release"
          sh "dotnet publish -p:Version=${VERSION} ClassifiedAds.BlazorServerSide/*.csproj --configuration Release"
          sh "dotnet publish -p:Version=${VERSION} ClassifiedAds.BlazorWebAssembly/*.csproj --configuration Release"
        }
      }
    }
  }
}