apiVersion: v1
kind: Service
metadata:
  labels:
    app: product-api
  name: product-api
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: product-api
status:
  loadBalancer: {}
