export const FETCH_AUDIT_LOGS = "FETCH_AUDIT_LOGS";
export const FETCH_AUDIT_LOGS_START = "FETCH_AUDIT_LOGS_START";
export const FETCH_AUDIT_LOGS_SUCCESS = "FETCH_AUDIT_LOGS_SUCCESS";
export const FETCH_AUDIT_LOGS_FAIL = "FETCH_AUDIT_LOGS_FAIL";
