export const FETCH_CONFIGURATION_ENTRIES = "FETCH_CONFIGURATION_ENTRIES";
export const FETCH_CONFIGURATION_ENTRIES_START =
  "FETCH_CONFIGURATION_ENTRIES_START";
export const FETCH_CONFIGURATION_ENTRIES_SUCCESS =
  "FETCH_CONFIGURATION_ENTRIES_SUCCESS";
export const FETCH_CONFIGURATION_ENTRIES_FAIL =
  "FETCH_CONFIGURATION_ENTRIES_FAIL";

export const FETCH_CONFIGURATION_ENTRY = "FETCH_CONFIGURATION_ENTRY";
export const FETCH_CONFIGURATION_ENTRY_START =
  "FETCH_CONFIGURATION_ENTRY_START";
export const FETCH_CONFIGURATION_ENTRY_SUCCESS =
  "FETCH_CONFIGURATION_ENTRY_SUCCESS";
export const FETCH_CONFIGURATION_ENTRY_FAIL = "FETCH_CONFIGURATION_ENTRY_FAIL";

export const UPDATE_CONFIGURATION_ENTRY = "UPDATE_CONFIGURATION_ENTRY";
export const RESET_CONFIGURATION_ENTRY = "RESET_CONFIGURATION_ENTRY";

export const SAVE_CONFIGURATION_ENTRY = "SAVE_CONFIGURATION_ENTRY";
export const SAVE_CONFIGURATION_ENTRY_START = "SAVE_CONFIGURATION_ENTRY_START";
export const SAVE_CONFIGURATION_ENTRY_SUCCESS =
  "SAVE_CONFIGURATION_ENTRY_SUCCESS";
export const SAVE_CONFIGURATION_ENTRY_FAIL = "SAVE_CONFIGURATION_ENTRY_FAIL";

export const DELETE_CONFIGURATION_ENTRY = "DELETE_CONFIGURATION_ENTRY";
export const DELETE_CONFIGURATION_ENTRY_START =
  "DELETE_CONFIGURATION_ENTRY_START";
export const DELETE_CONFIGURATION_ENTRY_SUCCESS =
  "DELETE_CONFIGURATION_ENTRY_SUCCESS";
export const DELETE_CONFIGURATION_ENTRY_FAIL =
  "DELETE_CONFIGURATION_ENTRY_FAIL";
