using ClassifiedAds.Domain.Entities;
using ClassifiedAds.Domain.Infrastructure.Storages;
using System.IO;
using System.Text;

namespace ClassifiedAds.Infrastructure.Storages.Fake
{
    public class FakeStorageManager : IFileStorageManager
    {
        public void Create(FileEntry fileEntry, MemoryStream stream)
        {
            fileEntry.FileLocation = "Fake.txt";
        }

        public void Delete(FileEntry fileEntry)
        {
            // do nothing
        }

        public byte[] Read(FileEntry fileEntry)
        {
            return Encoding.UTF8.GetBytes("The content is generated by Fake Storage Manager.");
        }
    }
}
