pipeline {
  agent any
  tools {
    nodejs "Default"
  }
  stages {
    stage('Git Checkout') {
      steps {
        git branch: 'master', url: 'https://github.com/phongnguyend/Practical.CleanArchitecture'
      }
    }
    stage('Install') {
      steps {
        sh 'node --version'
        sh 'npm --version'
        dir('src/UIs/reactjs') {
          sh 'npm install'
          sh 'npm audit --audit-level=critical'
        }
      }
    }
    stage('Build') {
      steps {
        dir('src/UIs/reactjs') {
          sh 'CI=false npm run build'
        }
      }
    }
  }
}