using ClassifiedAds.Domain.Infrastructure.Storages;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace ClassifiedAds.Infrastructure.Storages.Fake
{
    public class FakeStorageManager : IFileStorageManager
    {
        public void Create(IFileEntry fileEntry, Stream stream)
        {
            fileEntry.FileLocation = "Fake.txt";
        }

        public Task CreateAsync(IFileEntry fileEntry, Stream stream, CancellationToken cancellationToken = default)
        {
            Create(fileEntry, stream);
            return Task.CompletedTask;
        }

        public void Delete(IFileEntry fileEntry)
        {
            // do nothing
        }

        public Task DeleteAsync(IFileEntry fileEntry, CancellationToken cancellationToken = default)
        {
            return Task.CompletedTask;
        }

        public byte[] Read(IFileEntry fileEntry)
        {
            return Encoding.UTF8.GetBytes("The content is generated by Fake Storage Manager.");
        }

        public Task<byte[]> ReadAsync(IFileEntry fileEntry, CancellationToken cancellationToken = default)
        {
            return Task.FromResult(Read(fileEntry));
        }
    }
}
