FROM microsoft/dotnet:2.2-sdk AS build-env
WORKDIR /ClassifiedAds.Projects

# Copy csproj and restore as distinct layers
COPY ./ClassifiedAds.ApplicationServices/*.csproj ./ClassifiedAds.ApplicationServices/
COPY ./ClassifiedAds.BackgroundServices/*.csproj ./ClassifiedAds.BackgroundServices/
COPY ./ClassifiedAds.CrossCuttingConcerns/*.csproj ./ClassifiedAds.CrossCuttingConcerns/
COPY ./ClassifiedAds.Domain/*.csproj ./ClassifiedAds.Domain/
COPY ./ClassifiedAds.DomainServices/*.csproj ./ClassifiedAds.DomainServices/
COPY ./ClassifiedAds.DomainServices.UnitTests/*.csproj ./ClassifiedAds.DomainServices.UnitTests/
COPY ./ClassifiedAds.Identity/*.csproj ./ClassifiedAds.Identity/
COPY ./ClassifiedAds.IdentityServer/*.csproj ./ClassifiedAds.IdentityServer/
COPY ./ClassifiedAds.IdentityServer.Persistence/*.csproj ./ClassifiedAds.IdentityServer.Persistence/
COPY ./ClassifiedAds.Infrastructure/*.csproj ./ClassifiedAds.Infrastructure/
COPY ./ClassifiedAds.Infrastructure.Caching/*.csproj ./ClassifiedAds.Infrastructure.Caching/
COPY ./ClassifiedAds.Infrastructure.MessageBrokers/*.csproj ./ClassifiedAds.Infrastructure.MessageBrokers/
COPY ./ClassifiedAds.Infrastructure.Storages/*.csproj ./ClassifiedAds.Infrastructure.Storages/
COPY ./ClassifiedAds.Migrator/*.csproj ./ClassifiedAds.Migrator/
COPY ./ClassifiedAds.NotificationServer/*.csproj ./ClassifiedAds.NotificationServer/
COPY ./ClassifiedAds.NotificationTestClient/*.csproj ./ClassifiedAds.NotificationTestClient/
COPY ./ClassifiedAds.Persistence/*.csproj ./ClassifiedAds.Persistence/
COPY ./ClassifiedAds.WebAPI/*.csproj ./ClassifiedAds.WebAPI/
COPY ./ClassifiedAds.WebAPI.IntegrationTests/*.csproj ./ClassifiedAds.WebAPI.IntegrationTests/
COPY ./ClassifiedAds.WebMVC/*.csproj ./ClassifiedAds.WebMVC/
COPY ./ClassifiedAds.WebMVC.AutomationTests/*.csproj ./ClassifiedAds.WebMVC.AutomationTests/
COPY ./ClassifiedAds.Projects.sln .
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish ./ClassifiedAds.WebMVC/ClassifiedAds.WebMVC.csproj -c Release -o out

# Build runtime image
FROM microsoft/dotnet:2.2-aspnetcore-runtime
WORKDIR /ClassifiedAds.WebMVC
COPY --from=build-env /ClassifiedAds.Projects/ClassifiedAds.WebMVC/out .

HEALTHCHECK CMD curl --fail http://localhost:80/healthcheck || exit 1

ENTRYPOINT ["dotnet", "ClassifiedAds.WebMVC.dll"]