name: gitleaks --no-git

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: use gitleaks docker image
        run: |
          docker pull zricethezav/gitleaks:latest
          echo $GITHUB_WORKSPACE
          docker run -v $GITHUB_WORKSPACE:/path zricethezav/gitleaks:latest detect --source="/path" --config="/path/gitleaks.toml" --verbose --no-git
