name: Static Code Analysis UIs - ReactJs

on:
  push:
    branches:
      - master
      - build
    paths:
      - 'src/UIs/reactjs/**'
      - '.github/workflows/static-code-analysis-UIs-reactjs.yml'
  pull_request:
    paths: 
      - 'src/UIs/reactjs/**'
      - '.github/workflows/static-code-analysis-UIs-reactjs.yml'
  workflow_dispatch:
env:
  ENV_NAME: ENV_VALUE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: src/UIs/reactjs/
          args: >
            -Dsonar.organization=phongnguyend
            -Dsonar.projectKey=UIs_React
            -Dsonar.projectVersion=1.0.0.${{ github.run_number }}
